// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrope9InBdPGEmwHTcSVGMaEdDHWnO6M',
    appId: '1:367087248858:web:bea887c68f8f8353c2cce3',
    messagingSenderId: '367087248858',
    projectId: 'chat-app-5730c',
    authDomain: 'chat-app-5730c.firebaseapp.com',
    storageBucket: 'chat-app-5730c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpNbzVR5BN70AowDAco_knCqwbjFJb6vY',
    appId: '1:367087248858:android:2199c74e0fe79ea1c2cce3',
    messagingSenderId: '367087248858',
    projectId: 'chat-app-5730c',
    storageBucket: 'chat-app-5730c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB33RpTBFWM0oPp1LNgmAann8K5mDbKpqg',
    appId: '1:367087248858:ios:b60943f84dca9b64c2cce3',
    messagingSenderId: '367087248858',
    projectId: 'chat-app-5730c',
    storageBucket: 'chat-app-5730c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB33RpTBFWM0oPp1LNgmAann8K5mDbKpqg',
    appId: '1:367087248858:ios:b3e4241a8e2d2cf6c2cce3',
    messagingSenderId: '367087248858',
    projectId: 'chat-app-5730c',
    storageBucket: 'chat-app-5730c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
